# Generated by Django 6.0 on 2025-12-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_favorite_favoriteitem_history_movieframe_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_ru',
            field=models.TextField(null=True),
        ),
    ]
