# Generated by Django 6.0 on 2025-12-20 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_review_comment_en_review_comment_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='movievideo',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie_app.category'),
            preserve_default=False,
        ),
    ]
